name: bacon13
description: A Flutter social media app using Firebase.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Firebase dependencies
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  firebase_storage: ^11.5.6
  
  # UI and utilities
  cupertino_icons: ^1.0.2
  image_picker: ^1.0.4
  cached_network_image: ^3.3.0
  provider: ^6.1.1
  uuid: ^4.2.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  # Enable web support