// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB99as7K_bCTnGBoKk0U8w7T2P0Sk1S_dQ',
    appId: '1:1035009518967:web:612a98dac7120aa76e0572',
    messagingSenderId: '1035009518967',
    projectId: 'bacon13',
    authDomain: 'bacon13.firebaseapp.com',
    storageBucket: 'bacon13.firebasestorage.app',
    measurementId: 'G-VE5BCWN6HQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'your-android-api-key',
    appId: '1:123456789:android:abcdef',
    messagingSenderId: '123456789',
    projectId: 'bacon13',
    authDomain: 'bacon13.firebaseapp.com',
    storageBucket: 'bacon13.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'your-ios-api-key',
    appId: '1:123456789:ios:abcdef',
    messagingSenderId: '123456789',
    projectId: 'bacon13',
    authDomain: 'bacon13.firebaseapp.com',
    storageBucket: 'bacon13.appspot.com',
    iosBundleId: 'com.example.bacon13',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'your-macos-api-key',
    appId: '1:123456789:macos:abcdef',
    messagingSenderId: '123456789',
    projectId: 'bacon13',
    authDomain: 'bacon13.firebaseapp.com',
    storageBucket: 'bacon13.appspot.com',
    iosBundleId: 'com.example.bacon13',
  );
}